# endereço banco de dados
spring.datasource.url=jdbc:postgresql://ep-little-glitter-ac6o4lng.sa-east-1.aws.neon.tech/neondb?sslmode=require

# user name do serviço Neon
spring.datasource.username=neondb_owner

# senha
spring.datasource.password=${DB_PASSWORD}

# regra para o JPA criar as tabelas automaticamente e não apagar os dados
spring.jpa.hibernate.ddl-auto=update