# O endereço do teu banco na nuvem (repara que adicionei o prefixo 'jdbc:' que o Java exige)
spring.datasource.url=jdbc:postgresql://ep-little-glitter-ac6o4lng.sa-east-1.aws.neon.tech/neondb?sslmode=require

# O nome de utilizador gerado pelo Neon
spring.datasource.username=neondb_owner

# A tua password (vais ter de a substituir abaixo)
spring.datasource.password=${DB_PASSWORD}

# Regra de ouro para o JPA criar as tabelas automaticamente e não apagar os dados
spring.jpa.hibernate.ddl-auto=update